### ISSUE TITLE
multiping throws an exception if any of the hosts are not resolveable

### ISSUE THREAD

**Issue by lheckemann** [ValentinBELYN/icmplib#52]
```
>>> icmplib.multiping(["ping.lrz.de", "192.168.1.1"])
[<Host [129.187.10.17]>, <Host [192.168.1.1]>]
>>> icmplib.multiping(["ping.lrz.de", "192.168.1.1", "invalid.invalid"])
Traceback (most recent call last):
  File "/nix/store/kf6rq5lrpbvz9nivynbrjixz1xi36svb-python3.9-icmplib-3.0.2/lib/python3.9/site-packages/icmplib/utils.py", line 158, in async_resolve
    lookup = await loop.getaddrinfo(
  File "/nix/store/wq6s8i407ic4qp1dvd5yhrnd0kflzh6x-python3-3.9.12/lib/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "/nix/store/wq6s8i407ic4qp1dvd5yhrnd0kflzh6x-python3-3.9.12/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/wq6s8i407ic4qp1dvd5yhrnd0kflzh6x-python3-3.9.12/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/kf6rq5lrpbvz9nivynbrjixz1xi36svb-python3.9-icmplib-3.0.2/lib/python3.9/site-packages/icmplib/multiping.py", line 267, in multiping
    return asyncio.run(
  File "/nix/store/wq6s8i407ic4qp1dvd5yhrnd0kflzh6x-python3-3.9.12/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/wq6s8i407ic4qp1dvd5yhrnd0kflzh6x-python3-3.9.12/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/nix/store/kf6rq5lrpbvz9nivynbrjixz1xi36svb-python3.9-icmplib-3.0.2/lib/python3.9/site-packages/icmplib/multiping.py", line 163, in async_multiping
    return [task.result() for task in tasks]
  File "/nix/store/kf6rq5lrpbvz9nivynbrjixz1xi36svb-python3.9-icmplib-3.0.2/lib/python3.9/site-packages/icmplib/multiping.py", line 163, in <listcomp>
    return [task.result() for task in tasks]
  File "/nix/store/kf6rq5lrpbvz9nivynbrjixz1xi36svb-python3.9-icmplib-3.0.2/lib/python3.9/site-packages/icmplib/ping.py", line 263, in async_ping
    address = (await async_resolve(address, family))[0]
  File "/nix/store/kf6rq5lrpbvz9nivynbrjixz1xi36svb-python3.9-icmplib-3.0.2/lib/python3.9/site-packages/icmplib/utils.py", line 168, in async_resolve
    return await async_resolve(name, 6)
icmplib.exceptions.NameLookupError: The name 'invalid.invalid' cannot be resolved
```

My hope would be that even if one of the names cannot be looked up, a result would be returned for the others, and potentially that a result indicating the lookup failure would be given back for the unresolveable name.

**Comment by ValentinBELYN** [comment]
Hi @lheckemann!

I think these comments answer your question 😉:
- https://github.com/ValentinBELYN/icmplib/issues/44#issuecomment-1019554137
- https://github.com/ValentinBELYN/icmplib/issues/49#issuecomment-1086926139

**Comment by lheckemann** [comment]
Thanks!
